### ISSUE TITLE
Read Value Error when the sensor exceeds the 80000 lux 

### ISSUE THREAD

**Issue by Beerocket7** [RobTillaart/Max44009#15]

**Comment by RobTillaart** [comment]
Thanks for reporting, I will look into it coming days.

What values does it report, does it block or ?

What board are you using? (Just curious)

**Comment by RobTillaart** [comment]
@Beerocket7 

What settings do you use?  
Can you post your code?
What is the exact error code you get?

For high LUX rates you need to reduce integration time, and possibly use **MX.setManualMode(uint8_t CDR, uint8_t TIM) **

![image](https://github.com/RobTillaart/Max44009/assets/462844/7a9e5ee3-b17c-4972-a7e7-20ceb104c4f4)

**Comment by RobTillaart** [comment]
I noticed that reading back the CDR flag is missing.
I will add a **int getCurrentDivisorRatio()** function and make a develop branch.

**Comment by RobTillaart** [comment]
@Beerocket7 
Have you tried the other setting? 
If so did it solve your problem?

**Comment by RobTillaart** [comment]
As there are no answers to my questions I assume the problem is solved with the other settings.
Feel free to reopen the issue if the problem still exists.
